export const people = [
  {
    id: '1',
    name: 'Luke Skywalker',
    height: '172',
    hair_color: 'blond',
    eye_color: 'blue',
    gender: 'male',
  },
  {
    id: '2',
    name: 'C-3PO',
    height: '167',
    hair_color: 'n/a',
    eye_color: 'yellow',
    gender: 'n/a',
  },
  {
    id: '3',
    name: 'R2-D2',
    height: '96',
    hair_color: 'n/a',
    eye_color: 'red',
    gender: 'n/a',
  },
  {
    id: '4',
    name: 'Darth Vader',
    height: '202',
    hair_color: 'none',
    eye_color: 'yellow',
    gender: 'male',
  },
  {  
    id: '5',
    name: 'Leia Organa',
    height: '150',
    hair_color: 'brown',
    eye_color: 'brown',
    gender: 'female',
  },
]
